### ISSUE TITLE
Could you show your the full code

### ISSUE THREAD

**Issue by wlfjw12** [jmbenjamin/W-MV-PCM-L2#1]
I don't find the mvc_ex5_2clusts2viewswn.mat ,please could show your full code,in addition, is the input of W-MV-PCM-L2.m the multi-view data?

**Comment by jmbenjamin** [comment]
the mvc_ex5_2clusts2viewswn.mat is a synthetic multi-view dataset in matlab format that is used to test the algorithm. You may refer to some real datasets that I used in my study found in the dataset folder. If you have any questions, you may email me directly josephinebernadette@yahoo.com

**Comment by jmbenjamin** [comment]
the construction of mvc_ex5_2clusts2viewswn.mat dataset follows that kumar et al. P;ease read our paper and please cite our paper if you will use it as reference. Thank you

**Comment by wlfjw12** [comment]
> mvc_ex5_2clusts2viewswn.mat数据集的构建遵循kumar等人的观点。请轻松阅读我们的论文，如果您将其用作参考，请引用我们的论文。谢谢

 OK，Thank you very much！
